// Mesetorta.hu próbaadatok - adatbázis és API nélkül, későbbi fejlesztéshez.
//
// A rekordok kizárólag demó célú, kitalált mintaadatok. Nem valódi partnerek,
// nem valódi vállalkozások, és nem tartalmaznak külső képeket.
//
// Egységes adatmodell kapcsolatai:
// - partnerek: stabil partner_id azonosítóval kapcsolódnak városokhoz és körzetekhez.
// - tortak: partner_id, varos_id, korzet_id és kategoria_id alapján hivatkoznak a törzsadatokra.
// - varosok, korzetek, kategoriak: statikus törzsadatok a demó országos keresőhöz.

const varosok = [
  {
    "id": "varos_001",
    "nev": "Budapest",
    "kep_url": "kepek/placeholder/varos-placeholder.svg",
    "oldal": "varosok/budapest.html"
  },
  {
    "id": "varos_002",
    "nev": "Debrecen",
    "kep_url": "kepek/placeholder/varos-placeholder.svg",
    "oldal": "varosok/debrecen.html"
  },
  {
    "id": "varos_003",
    "nev": "Szeged",
    "kep_url": "kepek/placeholder/varos-placeholder.svg",
    "oldal": "varosok/szeged.html"
  },
  {
    "id": "varos_004",
    "nev": "Győr",
    "kep_url": "kepek/placeholder/varos-placeholder.svg",
    "oldal": "varosok/gyor.html"
  },
  {
    "id": "varos_005",
    "nev": "Pécs",
    "kep_url": "kepek/placeholder/varos-placeholder.svg",
    "oldal": "varosok/pecs.html"
  },
  {
    "id": "varos_006",
    "nev": "Miskolc",
    "kep_url": "kepek/placeholder/varos-placeholder.svg",
    "oldal": null
  },
  {
    "id": "varos_007",
    "nev": "Nyíregyháza",
    "kep_url": "kepek/placeholder/varos-placeholder.svg",
    "oldal": null
  },
  {
    "id": "varos_008",
    "nev": "Kecskemét",
    "kep_url": "kepek/placeholder/varos-placeholder.svg",
    "oldal": null
  },
  {
    "id": "varos_009",
    "nev": "Székesfehérvár",
    "kep_url": "kepek/placeholder/varos-placeholder.svg",
    "oldal": null
  },
  {
    "id": "varos_010",
    "nev": "Szombathely",
    "kep_url": "kepek/placeholder/varos-placeholder.svg",
    "oldal": null
  }
];

const korzetek = [
  {
    "id": "korzet_001",
    "varos_id": "varos_001",
    "nev": "I. kerület"
  },
  {
    "id": "korzet_002",
    "varos_id": "varos_001",
    "nev": "II. kerület"
  },
  {
    "id": "korzet_003",
    "varos_id": "varos_001",
    "nev": "III. kerület"
  },
  {
    "id": "korzet_004",
    "varos_id": "varos_001",
    "nev": "IV. kerület"
  },
  {
    "id": "korzet_005",
    "varos_id": "varos_001",
    "nev": "V. kerület"
  },
  {
    "id": "korzet_006",
    "varos_id": "varos_001",
    "nev": "VI. kerület"
  },
  {
    "id": "korzet_007",
    "varos_id": "varos_001",
    "nev": "VII. kerület"
  },
  {
    "id": "korzet_008",
    "varos_id": "varos_001",
    "nev": "VIII. kerület"
  },
  {
    "id": "korzet_009",
    "varos_id": "varos_001",
    "nev": "IX. kerület"
  },
  {
    "id": "korzet_010",
    "varos_id": "varos_001",
    "nev": "X. kerület"
  },
  {
    "id": "korzet_011",
    "varos_id": "varos_001",
    "nev": "XI. kerület"
  },
  {
    "id": "korzet_012",
    "varos_id": "varos_001",
    "nev": "XII. kerület"
  },
  {
    "id": "korzet_013",
    "varos_id": "varos_001",
    "nev": "XIII. kerület"
  },
  {
    "id": "korzet_014",
    "varos_id": "varos_001",
    "nev": "XIV. kerület"
  },
  {
    "id": "korzet_015",
    "varos_id": "varos_001",
    "nev": "XV. kerület"
  },
  {
    "id": "korzet_016",
    "varos_id": "varos_001",
    "nev": "XVI. kerület"
  },
  {
    "id": "korzet_017",
    "varos_id": "varos_001",
    "nev": "XVII. kerület"
  },
  {
    "id": "korzet_018",
    "varos_id": "varos_001",
    "nev": "XVIII. kerület"
  },
  {
    "id": "korzet_019",
    "varos_id": "varos_001",
    "nev": "XIX. kerület"
  },
  {
    "id": "korzet_020",
    "varos_id": "varos_001",
    "nev": "XX. kerület"
  },
  {
    "id": "korzet_021",
    "varos_id": "varos_001",
    "nev": "XXI. kerület"
  },
  {
    "id": "korzet_022",
    "varos_id": "varos_001",
    "nev": "XXII. kerület"
  },
  {
    "id": "korzet_023",
    "varos_id": "varos_001",
    "nev": "XXIII. kerület"
  },
  {
    "id": "korzet_024",
    "varos_id": "varos_002",
    "nev": "Belváros"
  },
  {
    "id": "korzet_025",
    "varos_id": "varos_002",
    "nev": "Nagyerdő"
  },
  {
    "id": "korzet_026",
    "varos_id": "varos_002",
    "nev": "Józsa"
  },
  {
    "id": "korzet_027",
    "varos_id": "varos_003",
    "nev": "Belváros"
  },
  {
    "id": "korzet_028",
    "varos_id": "varos_003",
    "nev": "Újszeged"
  },
  {
    "id": "korzet_029",
    "varos_id": "varos_003",
    "nev": "Móraváros"
  },
  {
    "id": "korzet_030",
    "varos_id": "varos_004",
    "nev": "Belváros"
  },
  {
    "id": "korzet_031",
    "varos_id": "varos_004",
    "nev": "Nádorváros"
  },
  {
    "id": "korzet_032",
    "varos_id": "varos_004",
    "nev": "Révfalu"
  },
  {
    "id": "korzet_033",
    "varos_id": "varos_005",
    "nev": "Belváros"
  },
  {
    "id": "korzet_034",
    "varos_id": "varos_005",
    "nev": "Tettye"
  },
  {
    "id": "korzet_035",
    "varos_id": "varos_005",
    "nev": "Uránváros"
  },
  {
    "id": "korzet_036",
    "varos_id": "varos_006",
    "nev": "Belváros"
  },
  {
    "id": "korzet_037",
    "varos_id": "varos_006",
    "nev": "Avas"
  },
  {
    "id": "korzet_038",
    "varos_id": "varos_007",
    "nev": "Belváros"
  },
  {
    "id": "korzet_039",
    "varos_id": "varos_007",
    "nev": "Sóstó"
  },
  {
    "id": "korzet_040",
    "varos_id": "varos_008",
    "nev": "Belváros"
  },
  {
    "id": "korzet_041",
    "varos_id": "varos_008",
    "nev": "Széchenyiváros"
  },
  {
    "id": "korzet_042",
    "varos_id": "varos_009",
    "nev": "Belváros"
  },
  {
    "id": "korzet_043",
    "varos_id": "varos_009",
    "nev": "Öreghegy"
  },
  {
    "id": "korzet_044",
    "varos_id": "varos_010",
    "nev": "Belváros"
  },
  {
    "id": "korzet_045",
    "varos_id": "varos_010",
    "nev": "Kámon"
  }
];

const kategoriak = [
  {
    "id": "kategoria_001",
    "nev": "Születésnapi torta"
  },
  {
    "id": "kategoria_002",
    "nev": "Gyerektorta"
  },
  {
    "id": "kategoria_003",
    "nev": "Esküvői torta"
  },
  {
    "id": "kategoria_004",
    "nev": "Ballagási torta"
  },
  {
    "id": "kategoria_005",
    "nev": "Keresztelő torta"
  },
  {
    "id": "kategoria_006",
    "nev": "Céges torta"
  },
  {
    "id": "kategoria_007",
    "nev": "Egyedi torta"
  },
  {
    "id": "kategoria_008",
    "nev": "Formatorta"
  },
  {
    "id": "kategoria_009",
    "nev": "Fotótorta"
  },
  {
    "id": "kategoria_010",
    "nev": "Sajttorta"
  },
  {
    "id": "kategoria_011",
    "nev": "Mini torta"
  },
  {
    "id": "kategoria_012",
    "nev": "Cukormentes torta"
  },
  {
    "id": "kategoria_013",
    "nev": "Gluténmentes torta"
  },
  {
    "id": "kategoria_014",
    "nev": "Vegán torta"
  },
  {
    "id": "kategoria_015",
    "nev": "Mentes torta"
  }
];

const partnerek = [
  {
    "id": "partner_001",
    "slug": "mesehab-cukraszda",
    "nev": "MeseHab Cukrászda",
    "tipus": "Cukrászda",
    "varos_id": "varos_001",
    "korzet_id": "korzet_013",
    "telefon": "+36 00 000 0001",
    "email": "demo.partner001@mesetorta.hu",
    "weboldal": "https://mesehab.example",
    "facebook": "https://www.facebook.com/mesehabcukraszda",
    "instagram": "https://www.instagram.com/mesehabcukraszda",
    "tiktok": "https://www.tiktok.com/@mesehabcukraszda",
    "bemutatkozas": "MeseHab Cukrászda kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "MeseHab Cukrászda minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "MeseHab Cukrászda minta borítókép",
    "kiemelt": true,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Budapest",
    "kerulet": "XIII. kerület",
    "korzet": "XIII. kerület",
    "cim": "XIII. kerület mintacím 1.",
    "leiras": "MeseHab Cukrászda nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": "partnerek/mesehab-cukraszda.html"
  },
  {
    "id": "partner_002",
    "slug": "tundersuti-muhely",
    "nev": "Tündérsüti Műhely",
    "tipus": "Tortaműhely",
    "varos_id": "varos_002",
    "korzet_id": "korzet_024",
    "telefon": "+36 00 000 0002",
    "email": "demo.partner002@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/tundersutimuhely",
    "tiktok": "",
    "bemutatkozas": "Tündérsüti Műhely kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Tündérsüti Műhely minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Tündérsüti Műhely minta borítókép",
    "kiemelt": true,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Debrecen",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cim": "Belváros mintacím 2.",
    "leiras": "Tündérsüti Műhely nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": "partnerek/tundersuti-muhely.html"
  },
  {
    "id": "partner_003",
    "slug": "cukorcsillag-tortamuhely",
    "nev": "Cukorcsillag Tortaműhely",
    "tipus": "Tortaműhely",
    "varos_id": "varos_003",
    "korzet_id": "korzet_028",
    "telefon": "+36 00 000 0003",
    "email": "demo.partner003@mesetorta.hu",
    "weboldal": "https://cukorcsillag.example",
    "facebook": "https://www.facebook.com/cukorcsillagtortamuhely",
    "instagram": "",
    "tiktok": "https://www.tiktok.com/@cukorcsillagtorta",
    "bemutatkozas": "Cukorcsillag Tortaműhely kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Cukorcsillag Tortaműhely minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Cukorcsillag Tortaműhely minta borítókép",
    "kiemelt": true,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Szeged",
    "kerulet": "Újszeged",
    "korzet": "Újszeged",
    "cim": "Újszeged mintacím 3.",
    "leiras": "Cukorcsillag Tortaműhely nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": "partnerek/cukorcsillag-tortamuhely.html"
  },
  {
    "id": "partner_004",
    "slug": "edes-mesek-cukraszda",
    "nev": "Édes Mesék Cukrászda",
    "tipus": "Cukrászda",
    "varos_id": "varos_005",
    "korzet_id": "korzet_034",
    "telefon": "+36 00 000 0004",
    "email": "demo.partner004@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Édes Mesék Cukrászda kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Édes Mesék Cukrászda minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Édes Mesék Cukrászda minta borítókép",
    "kiemelt": false,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Pécs",
    "kerulet": "Tettye",
    "korzet": "Tettye",
    "cim": "Tettye mintacím 4.",
    "leiras": "Édes Mesék Cukrászda nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  },
  {
    "id": "partner_005",
    "slug": "habfelho-cukraszda",
    "nev": "Habfelhő Cukrászda",
    "tipus": "Cukrászda",
    "varos_id": "varos_004",
    "korzet_id": "korzet_031",
    "telefon": "+36 00 000 0005",
    "email": "demo.partner005@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Habfelhő Cukrászda kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Habfelhő Cukrászda minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Habfelhő Cukrászda minta borítókép",
    "kiemelt": true,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Győr",
    "kerulet": "Nádorváros",
    "korzet": "Nádorváros",
    "cim": "Nádorváros mintacím 5.",
    "leiras": "Habfelhő Cukrászda nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  },
  {
    "id": "partner_006",
    "slug": "rozsakert-cukraszda",
    "nev": "Rózsakert Cukrászda",
    "tipus": "Cukrászda",
    "varos_id": "varos_006",
    "korzet_id": "korzet_037",
    "telefon": "+36 00 000 0006",
    "email": "demo.partner006@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Rózsakert Cukrászda kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Rózsakert Cukrászda minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Rózsakert Cukrászda minta borítókép",
    "kiemelt": false,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Miskolc",
    "kerulet": "Avas",
    "korzet": "Avas",
    "cim": "Avas mintacím 6.",
    "leiras": "Rózsakert Cukrászda nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  },
  {
    "id": "partner_007",
    "slug": "vaniliafeny-cukraszda",
    "nev": "Vaníliafény Cukrászda",
    "tipus": "Cukrászda",
    "varos_id": "varos_007",
    "korzet_id": "korzet_039",
    "telefon": "+36 00 000 0007",
    "email": "demo.partner007@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Vaníliafény Cukrászda kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Vaníliafény Cukrászda minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Vaníliafény Cukrászda minta borítókép",
    "kiemelt": false,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Nyíregyháza",
    "kerulet": "Sóstó",
    "korzet": "Sóstó",
    "cim": "Sóstó mintacím 7.",
    "leiras": "Vaníliafény Cukrászda nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  },
  {
    "id": "partner_008",
    "slug": "marcipanmanufaktura",
    "nev": "Marcipán Manufaktúra",
    "tipus": "Tortaműhely",
    "varos_id": "varos_008",
    "korzet_id": "korzet_041",
    "telefon": "+36 00 000 0008",
    "email": "demo.partner008@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Marcipán Manufaktúra kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Marcipán Manufaktúra minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Marcipán Manufaktúra minta borítókép",
    "kiemelt": true,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Kecskemét",
    "kerulet": "Széchenyiváros",
    "korzet": "Széchenyiváros",
    "cim": "Széchenyiváros mintacím 8.",
    "leiras": "Marcipán Manufaktúra nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  },
  {
    "id": "partner_009",
    "slug": "selyemkrem-muhely",
    "nev": "Selyemkrém Műhely",
    "tipus": "Tortaműhely",
    "varos_id": "varos_009",
    "korzet_id": "korzet_043",
    "telefon": "+36 00 000 0009",
    "email": "demo.partner009@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Selyemkrém Műhely kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Selyemkrém Műhely minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Selyemkrém Műhely minta borítókép",
    "kiemelt": false,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Székesfehérvár",
    "kerulet": "Öreghegy",
    "korzet": "Öreghegy",
    "cim": "Öreghegy mintacím 9.",
    "leiras": "Selyemkrém Műhely nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  },
  {
    "id": "partner_010",
    "slug": "habkarika-tortamuhely",
    "nev": "Habkarika Tortaműhely",
    "tipus": "Tortaműhely",
    "varos_id": "varos_010",
    "korzet_id": "korzet_045",
    "telefon": "+36 00 000 0010",
    "email": "demo.partner010@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Habkarika Tortaműhely kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Habkarika Tortaműhely minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Habkarika Tortaműhely minta borítókép",
    "kiemelt": false,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Szombathely",
    "kerulet": "Kámon",
    "korzet": "Kámon",
    "cim": "Kámon mintacím 10.",
    "leiras": "Habkarika Tortaműhely nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  },
  {
    "id": "partner_011",
    "slug": "otthoni-alomtorta",
    "nev": "Otthoni Álomtorta",
    "tipus": "Otthoni tortakészítő",
    "varos_id": "varos_001",
    "korzet_id": "korzet_011",
    "telefon": "+36 00 000 0011",
    "email": "demo.partner011@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Otthoni Álomtorta kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Otthoni Álomtorta minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Otthoni Álomtorta minta borítókép",
    "kiemelt": false,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Budapest",
    "kerulet": "XI. kerület",
    "korzet": "XI. kerület",
    "cim": "XI. kerület mintacím 11.",
    "leiras": "Otthoni Álomtorta nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  },
  {
    "id": "partner_012",
    "slug": "szivarvany-konyha",
    "nev": "Szivárvány Konyha",
    "tipus": "Otthoni tortakészítő",
    "varos_id": "varos_002",
    "korzet_id": "korzet_026",
    "telefon": "+36 00 000 0012",
    "email": "demo.partner012@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Szivárvány Konyha kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Szivárvány Konyha minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Szivárvány Konyha minta borítókép",
    "kiemelt": false,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Debrecen",
    "kerulet": "Józsa",
    "korzet": "Józsa",
    "cim": "Józsa mintacím 12.",
    "leiras": "Szivárvány Konyha nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  },
  {
    "id": "partner_013",
    "slug": "mezeskalacs-otthon",
    "nev": "Mézeskalács Otthon",
    "tipus": "Otthoni tortakészítő",
    "varos_id": "varos_003",
    "korzet_id": "korzet_029",
    "telefon": "+36 00 000 0013",
    "email": "demo.partner013@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Mézeskalács Otthon kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Mézeskalács Otthon minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Mézeskalács Otthon minta borítókép",
    "kiemelt": false,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Szeged",
    "kerulet": "Móraváros",
    "korzet": "Móraváros",
    "cim": "Móraváros mintacím 13.",
    "leiras": "Mézeskalács Otthon nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  },
  {
    "id": "partner_014",
    "slug": "kremvarazs-uzem",
    "nev": "Krémvarázs Cukrászüzem",
    "tipus": "Cukrászüzem",
    "varos_id": "varos_004",
    "korzet_id": "korzet_033",
    "telefon": "+36 00 000 0014",
    "email": "demo.partner014@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Krémvarázs Cukrászüzem kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Krémvarázs Cukrászüzem minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Krémvarázs Cukrászüzem minta borítókép",
    "kiemelt": true,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Győr",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cim": "Belváros mintacím 14.",
    "leiras": "Krémvarázs Cukrászüzem nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  },
  {
    "id": "partner_015",
    "slug": "edesmalom-uzem",
    "nev": "Édesmalom Cukrászüzem",
    "tipus": "Cukrászüzem",
    "varos_id": "varos_005",
    "korzet_id": "korzet_035",
    "telefon": "+36 00 000 0015",
    "email": "demo.partner015@mesetorta.hu",
    "weboldal": "",
    "facebook": "",
    "instagram": "",
    "tiktok": "",
    "bemutatkozas": "Édesmalom Cukrászüzem kitalált Mesetorta.hu demópartner, amely próbaadatként szerepel az országos tortakeresőben.",
    "logo_url": "kepek/placeholder/partner-logo-placeholder.svg",
    "logo_alt": "Édesmalom Cukrászüzem minta logó",
    "boritokep_url": "kepek/placeholder/partner-borito-placeholder.svg",
    "boritokep_alt": "Édesmalom Cukrászüzem minta borítókép",
    "kiemelt": false,
    "statusz": "aktiv",
    "kep": "kepek/placeholder/partner-logo-placeholder.svg",
    "varos": "Pécs",
    "kerulet": "Uránváros",
    "korzet": "Uránváros",
    "cim": "Uránváros mintacím 15.",
    "leiras": "Édesmalom Cukrászüzem nem valódi vállalkozás, kizárólag a Mesetorta.hu demó működését szemlélteti.",
    "oldal": null
  }
];

const tortak = [
  {
    "id": "torta_001",
    "slug": "erdei-gyumolcsos-alomtorta",
    "nev": "Erdei gyümölcsös álomtorta",
    "partner_id": "partner_001",
    "varos_id": "varos_001",
    "korzet_id": "korzet_013",
    "kategoria_id": "kategoria_001",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "12 900 Ft",
    "szeletszam": 12,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Erdei gyümölcsös álomtorta minta tortakép",
    "atveteli_informacio": "Ma 15:00-ig",
    "hatarido": "Ma 15:00-ig átvehető",
    "kiemelt": true,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Budapest",
    "kerulet": "XIII. kerület",
    "korzet": "XIII. kerület",
    "cukraszda": "MeseHab Cukrászda",
    "kategoria": "Születésnapi torta",
    "oldal": "tortak/erdei-gyumolcsos-alomtorta.html"
  },
  {
    "id": "torta_002",
    "slug": "csokolades-mogyoro-torta",
    "nev": "Csokoládés mogyoró torta",
    "partner_id": "partner_002",
    "varos_id": "varos_002",
    "korzet_id": "korzet_024",
    "kategoria_id": "kategoria_002",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "14 500 Ft",
    "szeletszam": 16,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Csokoládés mogyoró torta minta tortakép",
    "atveteli_informacio": "Ma 16:00-ig",
    "hatarido": "Ma 16:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Debrecen",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cukraszda": "Tündérsüti Műhely",
    "kategoria": "Gyerektorta",
    "oldal": "tortak/csokolades-mogyoro-torta.html"
  },
  {
    "id": "torta_007",
    "slug": "unikornis-szulinapi-torta",
    "nev": "Unikornis szülinapi torta",
    "partner_id": "partner_001",
    "varos_id": "varos_001",
    "korzet_id": "korzet_011",
    "kategoria_id": "kategoria_002",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "18 900 Ft-tól",
    "szeletszam": 16,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Unikornis szülinapi torta minta tortakép",
    "atveteli_informacio": "Rendelhető 5 nap alatt",
    "hatarido": "Rendelési határidő: 5 nap",
    "kiemelt": true,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Budapest",
    "kerulet": "XI. kerület",
    "korzet": "XI. kerület",
    "cukraszda": "MeseHab Cukrászda",
    "kategoria": "Gyerektorta",
    "oldal": "tortak/unikornis-szulinapi-torta.html"
  },
  {
    "id": "torta_004",
    "slug": "ballagasi-vaniliakrem-torta",
    "nev": "Ballagási vaníliakrém torta",
    "partner_id": "partner_003",
    "varos_id": "varos_003",
    "korzet_id": "korzet_027",
    "kategoria_id": "kategoria_004",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "22 900 Ft-tól",
    "szeletszam": 20,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Ballagási vaníliakrém torta minta tortakép",
    "atveteli_informacio": "Rendelhető 6 nap alatt",
    "hatarido": "Rendelési határidő: 6 nap",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Szeged",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cukraszda": "Cukorcsillag Tortaműhely",
    "kategoria": "Ballagási torta",
    "oldal": null
  },
  {
    "id": "torta_005",
    "slug": "keresztelo-feherhab-torta",
    "nev": "Keresztelő fehérhab torta",
    "partner_id": "partner_004",
    "varos_id": "varos_005",
    "korzet_id": "korzet_034",
    "kategoria_id": "kategoria_005",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "19 800 Ft-tól",
    "szeletszam": 18,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Keresztelő fehérhab torta minta tortakép",
    "atveteli_informacio": "Rendelhető 7 nap alatt",
    "hatarido": "Rendelési határidő: 7 nap",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Pécs",
    "kerulet": "Tettye",
    "korzet": "Tettye",
    "cukraszda": "Édes Mesék Cukrászda",
    "kategoria": "Keresztelő torta",
    "oldal": null
  },
  {
    "id": "torta_006",
    "slug": "ceges-kavekrem-torta",
    "nev": "Céges kávékrém torta",
    "partner_id": "partner_005",
    "varos_id": "varos_004",
    "korzet_id": "korzet_031",
    "kategoria_id": "kategoria_006",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "27 500 Ft-tól",
    "szeletszam": 24,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Céges kávékrém torta minta tortakép",
    "atveteli_informacio": "Rendelhető 8 nap alatt",
    "hatarido": "Rendelési határidő: 8 nap",
    "kiemelt": true,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Győr",
    "kerulet": "Nádorváros",
    "korzet": "Nádorváros",
    "cukraszda": "Habfelhő Cukrászda",
    "kategoria": "Céges torta",
    "oldal": null
  },
  {
    "id": "torta_003",
    "slug": "egyedi-mesevaro-torta",
    "nev": "Egyedi meseváró torta",
    "partner_id": "partner_006",
    "varos_id": "varos_006",
    "korzet_id": "korzet_037",
    "kategoria_id": "kategoria_007",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "25 900 Ft-tól",
    "szeletszam": 20,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Egyedi meseváró torta minta tortakép",
    "atveteli_informacio": "Rendelhető 9 nap alatt",
    "hatarido": "Rendelési határidő: 9 nap",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Miskolc",
    "kerulet": "Avas",
    "korzet": "Avas",
    "cukraszda": "Rózsakert Cukrászda",
    "kategoria": "Egyedi torta",
    "oldal": null
  },
  {
    "id": "torta_008",
    "slug": "marcipanos-mesefigura-torta",
    "nev": "Marcipános mesefigura torta",
    "partner_id": "partner_008",
    "varos_id": "varos_008",
    "korzet_id": "korzet_041",
    "kategoria_id": "kategoria_008",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "24 900 Ft-tól",
    "szeletszam": 18,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Marcipános mesefigura torta minta tortakép",
    "atveteli_informacio": "Rendelhető 10 nap alatt",
    "hatarido": "Rendelési határidő: 10 nap",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Kecskemét",
    "kerulet": "Széchenyiváros",
    "korzet": "Széchenyiváros",
    "cukraszda": "Marcipán Manufaktúra",
    "kategoria": "Formatorta",
    "oldal": null
  },
  {
    "id": "torta_009",
    "slug": "fotoemlek-torta",
    "nev": "Fotóemlék torta",
    "partner_id": "partner_009",
    "varos_id": "varos_009",
    "korzet_id": "korzet_043",
    "kategoria_id": "kategoria_009",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "20 900 Ft-tól",
    "szeletszam": 16,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Fotóemlék torta minta tortakép",
    "atveteli_informacio": "Rendelhető 2 nap alatt",
    "hatarido": "Rendelési határidő: 2 nap",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Székesfehérvár",
    "kerulet": "Öreghegy",
    "korzet": "Öreghegy",
    "cukraszda": "Selyemkrém Műhely",
    "kategoria": "Fotótorta",
    "oldal": null
  },
  {
    "id": "torta_010",
    "slug": "karamellas-sajttorta",
    "nev": "Karamellás sajttorta",
    "partner_id": "partner_004",
    "varos_id": "varos_005",
    "korzet_id": "korzet_034",
    "kategoria_id": "kategoria_010",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "13 200 Ft",
    "szeletszam": 12,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Karamellás sajttorta minta tortakép",
    "atveteli_informacio": "Ma 18:00-ig",
    "hatarido": "Ma 18:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Pécs",
    "kerulet": "Tettye",
    "korzet": "Tettye",
    "cukraszda": "Édes Mesék Cukrászda",
    "kategoria": "Sajttorta",
    "oldal": null
  },
  {
    "id": "torta_011",
    "slug": "mini-malnas-torta",
    "nev": "Mini málnás torta",
    "partner_id": "partner_010",
    "varos_id": "varos_010",
    "korzet_id": "korzet_045",
    "kategoria_id": "kategoria_011",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "7 900 Ft",
    "szeletszam": 6,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Mini málnás torta minta tortakép",
    "atveteli_informacio": "Ma 19:00-ig",
    "hatarido": "Ma 19:00-ig átvehető",
    "kiemelt": true,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Szombathely",
    "kerulet": "Kámon",
    "korzet": "Kámon",
    "cukraszda": "Habkarika Tortaműhely",
    "kategoria": "Mini torta",
    "oldal": null
  },
  {
    "id": "torta_012",
    "slug": "cukormentes-almas-torta",
    "nev": "Cukormentes almás torta",
    "partner_id": "partner_011",
    "varos_id": "varos_001",
    "korzet_id": "korzet_014",
    "kategoria_id": "kategoria_012",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "11 900 Ft",
    "szeletszam": 10,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Cukormentes almás torta minta tortakép",
    "atveteli_informacio": "Ma 14:00-ig",
    "hatarido": "Ma 14:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Budapest",
    "kerulet": "XIV. kerület",
    "korzet": "XIV. kerület",
    "cukraszda": "Otthoni Álomtorta",
    "kategoria": "Cukormentes torta",
    "oldal": null
  },
  {
    "id": "torta_013",
    "slug": "glutenmentes-csokitorta",
    "nev": "Gluténmentes csokitorta",
    "partner_id": "partner_003",
    "varos_id": "varos_003",
    "korzet_id": "korzet_028",
    "kategoria_id": "kategoria_013",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "16 500 Ft-tól",
    "szeletszam": 12,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Gluténmentes csokitorta minta tortakép",
    "atveteli_informacio": "Rendelhető 6 nap alatt",
    "hatarido": "Rendelési határidő: 6 nap",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Szeged",
    "kerulet": "Újszeged",
    "korzet": "Újszeged",
    "cukraszda": "Cukorcsillag Tortaműhely",
    "kategoria": "Gluténmentes torta",
    "oldal": null
  },
  {
    "id": "torta_014",
    "slug": "vegan-malnas-csokoladetorta",
    "nev": "Vegán málnás csokoládétorta",
    "partner_id": "partner_012",
    "varos_id": "varos_002",
    "korzet_id": "korzet_026",
    "kategoria_id": "kategoria_014",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "17 900 Ft-tól",
    "szeletszam": 12,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Vegán málnás csokoládétorta minta tortakép",
    "atveteli_informacio": "Rendelhető 7 nap alatt",
    "hatarido": "Rendelési határidő: 7 nap",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Debrecen",
    "kerulet": "Józsa",
    "korzet": "Józsa",
    "cukraszda": "Szivárvány Konyha",
    "kategoria": "Vegán torta",
    "oldal": null
  },
  {
    "id": "torta_015",
    "slug": "mentes-afonyas-torta",
    "nev": "Mentes áfonyás torta",
    "partner_id": "partner_013",
    "varos_id": "varos_003",
    "korzet_id": "korzet_029",
    "kategoria_id": "kategoria_015",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "18 400 Ft-tól",
    "szeletszam": 14,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Mentes áfonyás torta minta tortakép",
    "atveteli_informacio": "Rendelhető 8 nap alatt",
    "hatarido": "Rendelési határidő: 8 nap",
    "kiemelt": true,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Szeged",
    "kerulet": "Móraváros",
    "korzet": "Móraváros",
    "cukraszda": "Mézeskalács Otthon",
    "kategoria": "Mentes torta",
    "oldal": null
  },
  {
    "id": "torta_016",
    "slug": "szulinapi-konfetti-torta",
    "nev": "Születésnapi konfetti torta",
    "partner_id": "partner_005",
    "varos_id": "varos_004",
    "korzet_id": "korzet_032",
    "kategoria_id": "kategoria_001",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "12 400 Ft",
    "szeletszam": 12,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Születésnapi konfetti torta minta tortakép",
    "atveteli_informacio": "Ma 18:00-ig",
    "hatarido": "Ma 18:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Győr",
    "kerulet": "Révfalu",
    "korzet": "Révfalu",
    "cukraszda": "Habfelhő Cukrászda",
    "kategoria": "Születésnapi torta",
    "oldal": null
  },
  {
    "id": "torta_017",
    "slug": "dinokalapos-gyerektorta",
    "nev": "Dinókalapos gyerektorta",
    "partner_id": "partner_006",
    "varos_id": "varos_006",
    "korzet_id": "korzet_038",
    "kategoria_id": "kategoria_002",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "13 900 Ft",
    "szeletszam": 10,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Dinókalapos gyerektorta minta tortakép",
    "atveteli_informacio": "Ma 19:00-ig",
    "hatarido": "Ma 19:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Miskolc",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cukraszda": "Rózsakert Cukrászda",
    "kategoria": "Gyerektorta",
    "oldal": null
  },
  {
    "id": "torta_018",
    "slug": "eskuvoi-rozsakrem-torta",
    "nev": "Esküvői fehér rózsatorta",
    "partner_id": "partner_002",
    "varos_id": "varos_002",
    "korzet_id": "korzet_025",
    "kategoria_id": "kategoria_003",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "39 900 Ft-tól",
    "szeletszam": 32,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Esküvői fehér rózsatorta minta tortakép",
    "atveteli_informacio": "Rendelhető 2 nap alatt",
    "hatarido": "Rendelési határidő: 2 nap",
    "kiemelt": true,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Debrecen",
    "kerulet": "Nagyerdő",
    "korzet": "Nagyerdő",
    "cukraszda": "Tündérsüti Műhely",
    "kategoria": "Esküvői torta",
    "oldal": null
  },
  {
    "id": "torta_019",
    "slug": "ballagas-konyv-torta",
    "nev": "Ballagás könyv torta",
    "partner_id": "partner_014",
    "varos_id": "varos_004",
    "korzet_id": "korzet_033",
    "kategoria_id": "kategoria_004",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "16 900 Ft",
    "szeletszam": 18,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Ballagás könyv torta minta tortakép",
    "atveteli_informacio": "Ma 15:00-ig",
    "hatarido": "Ma 15:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Győr",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cukraszda": "Krémvarázs Cukrászüzem",
    "kategoria": "Ballagási torta",
    "oldal": null
  },
  {
    "id": "torta_020",
    "slug": "keresztelo-csipke-torta",
    "nev": "Keresztelő csipketorta",
    "partner_id": "partner_007",
    "varos_id": "varos_007",
    "korzet_id": "korzet_039",
    "kategoria_id": "kategoria_005",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "15 700 Ft",
    "szeletszam": 14,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Keresztelő csipketorta minta tortakép",
    "atveteli_informacio": "Ma 16:00-ig",
    "hatarido": "Ma 16:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Nyíregyháza",
    "kerulet": "Sóstó",
    "korzet": "Sóstó",
    "cukraszda": "Vaníliafény Cukrászda",
    "kategoria": "Keresztelő torta",
    "oldal": null
  },
  {
    "id": "torta_021",
    "slug": "ceges-logominta-torta",
    "nev": "Céges logóminta torta",
    "partner_id": "partner_008",
    "varos_id": "varos_008",
    "korzet_id": "korzet_042",
    "kategoria_id": "kategoria_006",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "29 900 Ft-tól",
    "szeletszam": 24,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Céges logóminta torta minta tortakép",
    "atveteli_informacio": "Rendelhető 5 nap alatt",
    "hatarido": "Rendelési határidő: 5 nap",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Kecskemét",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cukraszda": "Marcipán Manufaktúra",
    "kategoria": "Céges torta",
    "oldal": null
  },
  {
    "id": "torta_022",
    "slug": "egyedi-viragkert-torta",
    "nev": "Egyedi virágkert torta",
    "partner_id": "partner_009",
    "varos_id": "varos_009",
    "korzet_id": "korzet_044",
    "kategoria_id": "kategoria_007",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "18 900 Ft",
    "szeletszam": 16,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Egyedi virágkert torta minta tortakép",
    "atveteli_informacio": "Ma 18:00-ig",
    "hatarido": "Ma 18:00-ig átvehető",
    "kiemelt": true,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Székesfehérvár",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cukraszda": "Selyemkrém Műhely",
    "kategoria": "Egyedi torta",
    "oldal": null
  },
  {
    "id": "torta_023",
    "slug": "versenyauto-formatorta",
    "nev": "Versenyautó formatorta",
    "partner_id": "partner_010",
    "varos_id": "varos_010",
    "korzet_id": "korzet_045",
    "kategoria_id": "kategoria_008",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "26 900 Ft-tól",
    "szeletszam": 18,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Versenyautó formatorta minta tortakép",
    "atveteli_informacio": "Rendelhető 7 nap alatt",
    "hatarido": "Rendelési határidő: 7 nap",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Szombathely",
    "kerulet": "Kámon",
    "korzet": "Kámon",
    "cukraszda": "Habkarika Tortaműhely",
    "kategoria": "Formatorta",
    "oldal": null
  },
  {
    "id": "torta_024",
    "slug": "fenykepes-csaladi-torta",
    "nev": "Fényképes családi torta",
    "partner_id": "partner_011",
    "varos_id": "varos_001",
    "korzet_id": "korzet_018",
    "kategoria_id": "kategoria_009",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "14 900 Ft",
    "szeletszam": 12,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Fényképes családi torta minta tortakép",
    "atveteli_informacio": "Ma 14:00-ig",
    "hatarido": "Ma 14:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Budapest",
    "kerulet": "XVIII. kerület",
    "korzet": "XVIII. kerület",
    "cukraszda": "Otthoni Álomtorta",
    "kategoria": "Fotótorta",
    "oldal": null
  },
  {
    "id": "torta_025",
    "slug": "mangos-sajttorta",
    "nev": "Mangós sajttorta",
    "partner_id": "partner_012",
    "varos_id": "varos_002",
    "korzet_id": "korzet_024",
    "kategoria_id": "kategoria_010",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "12 800 Ft",
    "szeletszam": 10,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Mangós sajttorta minta tortakép",
    "atveteli_informacio": "Ma 15:00-ig",
    "hatarido": "Ma 15:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Debrecen",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cukraszda": "Szivárvány Konyha",
    "kategoria": "Sajttorta",
    "oldal": null
  },
  {
    "id": "torta_026",
    "slug": "mini-csoki-trio-torta",
    "nev": "Mini csoki trió torta",
    "partner_id": "partner_013",
    "varos_id": "varos_003",
    "korzet_id": "korzet_027",
    "kategoria_id": "kategoria_011",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "8 900 Ft",
    "szeletszam": 6,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Mini csoki trió torta minta tortakép",
    "atveteli_informacio": "Ma 16:00-ig",
    "hatarido": "Ma 16:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Szeged",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cukraszda": "Mézeskalács Otthon",
    "kategoria": "Mini torta",
    "oldal": null
  },
  {
    "id": "torta_027",
    "slug": "cukormentes-meggyes-torta",
    "nev": "Cukormentes meggyes torta",
    "partner_id": "partner_014",
    "varos_id": "varos_004",
    "korzet_id": "korzet_031",
    "kategoria_id": "kategoria_012",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "13 600 Ft",
    "szeletszam": 12,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Cukormentes meggyes torta minta tortakép",
    "atveteli_informacio": "Ma 17:00-ig",
    "hatarido": "Ma 17:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Győr",
    "kerulet": "Nádorváros",
    "korzet": "Nádorváros",
    "cukraszda": "Krémvarázs Cukrászüzem",
    "kategoria": "Cukormentes torta",
    "oldal": null
  },
  {
    "id": "torta_028",
    "slug": "glutenmentes-vanilia-torta",
    "nev": "Gluténmentes vanília torta",
    "partner_id": "partner_015",
    "varos_id": "varos_005",
    "korzet_id": "korzet_036",
    "kategoria_id": "kategoria_013",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "14 300 Ft",
    "szeletszam": 12,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Gluténmentes vanília torta minta tortakép",
    "atveteli_informacio": "Ma 18:00-ig",
    "hatarido": "Ma 18:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Pécs",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cukraszda": "Édesmalom Cukrászüzem",
    "kategoria": "Gluténmentes torta",
    "oldal": null
  },
  {
    "id": "torta_029",
    "slug": "vegan-citromos-torta",
    "nev": "Vegán citromos torta",
    "partner_id": "partner_007",
    "varos_id": "varos_007",
    "korzet_id": "korzet_040",
    "kategoria_id": "kategoria_014",
    "allapot": "keszleten",
    "statusz": "aktiv",
    "ar": "12 600 Ft",
    "szeletszam": 10,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Vegán citromos torta minta tortakép",
    "atveteli_informacio": "Ma 19:00-ig",
    "hatarido": "Ma 19:00-ig átvehető",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Nyíregyháza",
    "kerulet": "Belváros",
    "korzet": "Belváros",
    "cukraszda": "Vaníliafény Cukrászda",
    "kategoria": "Vegán torta",
    "oldal": null
  },
  {
    "id": "torta_030",
    "slug": "mentes-kokuszos-torta",
    "nev": "Mentes kókuszos torta",
    "partner_id": "partner_015",
    "varos_id": "varos_005",
    "korzet_id": "korzet_035",
    "kategoria_id": "kategoria_015",
    "allapot": "rendelheto",
    "statusz": "aktiv",
    "ar": "19 900 Ft-tól",
    "szeletszam": 16,
    "kep_url": "kepek/placeholder/torta-placeholder.svg",
    "kep_alt": "Mentes kókuszos torta minta tortakép",
    "atveteli_informacio": "Rendelhető 5 nap alatt",
    "hatarido": "Rendelési határidő: 5 nap",
    "kiemelt": false,
    "aktiv": true,
    "kep": "kepek/placeholder/torta-placeholder.svg",
    "varos": "Pécs",
    "kerulet": "Uránváros",
    "korzet": "Uránváros",
    "cukraszda": "Édesmalom Cukrászüzem",
    "kategoria": "Mentes torta",
    "oldal": null
  }
];

const azonnalAtvehetoTortak = tortak.filter((torta) => torta.allapot === 'keszleten');
const rendelhetoTortak = tortak.filter((torta) => torta.allapot === 'rendelheto');
const cukraszdak = partnerek;

window.MESETORTA_ADATOK = {
  varosok,
  korzetek,
  kategoriak,
  partnerek,
  tortak,
  azonnalAtvehetoTortak,
  rendelhetoTortak,
  cukraszdak
};
