// MESETORTA próbaadatok - adatbázis nélkül, későbbi fejlesztéshez.

const azonnalAtvehetoTortak = [
  {
    id: 'keszleten-001',
    nev: 'Erdei gyümölcsös álomtorta',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '12 900 Ft',
    varos: 'Budapest',
    kerulet: 'XIII. kerület',
    korzet: 'XIII. kerület',
    cukraszda: 'MeseHab Cukrászda',
    allapot: 'keszleten',
    hatarido: 'Ma 16:00-ig átvehető',
    atveteli_informacio: 'Ma 16:00-ig',
    kategoria: 'Gyümölcsös torta',
    szeletszam: 12
  },
  {
    id: 'keszleten-002',
    nev: 'Csokoládés mogyoró torta',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '14 500 Ft',
    varos: 'Debrecen',
    kerulet: 'Belváros',
    korzet: 'Belváros',
    cukraszda: 'Tündérsüti Műhely',
    allapot: 'keszleten',
    hatarido: 'Ma 18:00-ig átvehető',
    atveteli_informacio: 'Ma 18:00-ig',
    kategoria: 'Csokoládétorta',
    szeletszam: 16
  },
  {
    id: 'keszleten-003',
    nev: 'Vaníliás eper torta',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '11 800 Ft',
    varos: 'Szeged',
    kerulet: 'Újszeged',
    korzet: 'Újszeged',
    cukraszda: 'Cukorcsillag Tortaműhely',
    allapot: 'keszleten',
    hatarido: 'Ma 17:30-ig átvehető',
    atveteli_informacio: 'Ma 17:30-ig',
    kategoria: 'Tejszínes torta',
    szeletszam: 10
  },
  {
    id: 'keszleten-004',
    nev: 'Karamellás sajttorta',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '13 200 Ft',
    varos: 'Pécs',
    kerulet: 'Tettye',
    korzet: 'Tettye',
    cukraszda: 'Édes Mesék Cukrászda',
    allapot: 'keszleten',
    hatarido: 'Ma 15:00-ig átvehető',
    atveteli_informacio: 'Ma 15:00-ig',
    kategoria: 'Sajttorta',
    szeletszam: 12
  },
  {
    id: 'keszleten-005',
    nev: 'Dobos torta szeletelt díszítéssel',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '15 900 Ft',
    varos: 'Győr',
    kerulet: 'Nádorváros',
    korzet: 'Nádorváros',
    cukraszda: 'MeseHab Cukrászda',
    allapot: 'keszleten',
    hatarido: 'Ma 19:00-ig átvehető',
    atveteli_informacio: 'Ma 19:00-ig',
    kategoria: 'Klasszikus torta',
    szeletszam: 16
  },
  {
    id: 'keszleten-006',
    nev: 'Citromos habkönnyű torta',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '10 900 Ft',
    varos: 'Miskolc',
    kerulet: 'Avas',
    korzet: 'Avas',
    cukraszda: 'Tündérsüti Műhely',
    allapot: 'keszleten',
    hatarido: 'Ma 16:30-ig átvehető',
    atveteli_informacio: 'Ma 16:30-ig',
    kategoria: 'Gyümölcsös torta',
    szeletszam: 8
  }
];

const rendelhetoTortak = [
  {
    id: 'rendelheto-001',
    nev: 'Unikornis szülinapi torta',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '18 900 Ft-tól',
    varos: 'Budapest',
    kerulet: 'XI. kerület',
    korzet: 'XI. kerület',
    cukraszda: 'MeseHab Cukrászda',
    allapot: 'rendelheto',
    hatarido: 'Rendelési határidő: 3 nap',
    atveteli_informacio: 'Rendelhető 3 nap alatt',
    kategoria: 'Gyerektorta',
    szeletszam: 16
  },
  {
    id: 'rendelheto-002',
    nev: 'Esküvői fehér rózsatorta',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '39 900 Ft-tól',
    varos: 'Debrecen',
    kerulet: 'Nagyerdő',
    korzet: 'Nagyerdő',
    cukraszda: 'Tündérsüti Műhely',
    allapot: 'rendelheto',
    hatarido: 'Rendelési határidő: 10 nap',
    atveteli_informacio: 'Rendelhető 10 nap alatt',
    kategoria: 'Esküvői torta',
    szeletszam: 32
  },
  {
    id: 'rendelheto-003',
    nev: 'Gluténmentes csokitorta',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '16 500 Ft-tól',
    varos: 'Szeged',
    kerulet: 'Belváros',
    korzet: 'Belváros',
    cukraszda: 'Cukorcsillag Tortaműhely',
    allapot: 'rendelheto',
    hatarido: 'Rendelési határidő: 4 nap',
    atveteli_informacio: 'Rendelhető 4 nap alatt',
    kategoria: 'Mentes torta',
    szeletszam: 12
  },
  {
    id: 'rendelheto-004',
    nev: 'Macaron díszes ünnepi torta',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '21 900 Ft-tól',
    varos: 'Pécs',
    kerulet: 'Belváros',
    korzet: 'Belváros',
    cukraszda: 'Édes Mesék Cukrászda',
    allapot: 'rendelheto',
    hatarido: 'Rendelési határidő: 5 nap',
    atveteli_informacio: 'Rendelhető 5 nap alatt',
    kategoria: 'Ünnepi torta',
    szeletszam: 20
  },
  {
    id: 'rendelheto-005',
    nev: 'Marcipános mesefigura torta',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '24 900 Ft-tól',
    varos: 'Győr',
    kerulet: 'Belváros',
    korzet: 'Belváros',
    cukraszda: 'MeseHab Cukrászda',
    allapot: 'rendelheto',
    hatarido: 'Rendelési határidő: 6 nap',
    atveteli_informacio: 'Rendelhető 6 nap alatt',
    kategoria: 'Formatorta',
    szeletszam: 18
  },
  {
    id: 'rendelheto-006',
    nev: 'Vegán málnás csokoládétorta',
    kep: 'kepek/torta-placeholder.jpg',
    ar: '17 900 Ft-tól',
    varos: 'Miskolc',
    kerulet: 'Belváros',
    korzet: 'Belváros',
    cukraszda: 'Tündérsüti Műhely',
    allapot: 'rendelheto',
    hatarido: 'Rendelési határidő: 4 nap',
    atveteli_informacio: 'Rendelhető 4 nap alatt',
    kategoria: 'Mentes torta',
    szeletszam: 12
  }
];

const cukraszdak = [
  {
    id: 'cukraszda-001',
    nev: 'MeseHab Cukrászda',
    kep: 'kepek/torta-placeholder.jpg',
    varos: 'Budapest',
    kerulet: 'XIII. kerület',
    korzet: 'XIII. kerület',
    tipus: 'Cukrászda',
    kiemelt: true,
    cim: 'Mese utca 12.',
    leiras: 'Klasszikus és mesés születésnapi torták készítése rövid határidővel.'
  },
  {
    id: 'cukraszda-002',
    nev: 'Tündérsüti Műhely',
    kep: 'kepek/torta-placeholder.jpg',
    varos: 'Debrecen',
    kerulet: 'Belváros',
    korzet: 'Belváros',
    tipus: 'Tortaműhely',
    kiemelt: true,
    cim: 'Tündér tér 4.',
    leiras: 'Rendelhető alkalmi torták, mentes sütemények és családi ünnepi desszertek.'
  },
  {
    id: 'cukraszda-003',
    nev: 'Cukorcsillag Tortaműhely',
    kep: 'kepek/torta-placeholder.jpg',
    varos: 'Szeged',
    kerulet: 'Újszeged',
    korzet: 'Újszeged',
    tipus: 'Tortaműhely',
    kiemelt: true,
    cim: 'Csillag sétány 8.',
    leiras: 'Egyedi díszítésű torták gyerekzsúrokra, céges eseményekre és esküvőkre.'
  },
  {
    id: 'cukraszda-004',
    nev: 'Édes Mesék Cukrászda',
    kep: 'kepek/torta-placeholder.jpg',
    varos: 'Pécs',
    kerulet: 'Tettye',
    korzet: 'Tettye',
    tipus: 'Cukrászda',
    kiemelt: false,
    cim: 'Édes köz 3.',
    leiras: 'Házi ízvilágú torták, szezonális krémek és hagyományos cukrászsütemények.'
  }
];
